#!/bin/bash

if [ $1 == "l" ]
then
    # Firefox
    cp -vr ~/.mozilla/firefox/3ccio4xn.default-nightly/chrome/userChrome-light.css ~/.mozilla/firefox/3ccio4xn.default-nightly/chrome/userChrome.css
    # Wallpaper
    feh --bg-fill /home/mir/Pictures/Anime/EQRUXU4WsAYw3kE.jpg
    # Alacritty
    cp ~/.config/alacritty/alacritty-light.yml ~/.config/alacritty/alacritty.yml
    # Kitty
    sed -i "s/nord/polar/g" ~/.config/kitty/kitty.conf
    # Global theme
    dconf dump '/org/cinnamon/' > ~/.dconf/cinnamon.dconf
    sed -i "s/Nord/WhiteSur-light/g" ~/.dconf/cinnamon.dconf
    sed -i "s/Adapta-Nokto/WhiteSur-light/g" ~/.dconf/cinnamon.dconf
    dconf load '/org/cinnamon/' < ~/.dconf/cinnamon.dconf
    # Vim
    sed -i "s/colorscheme nord/colorscheme one/g" ~/.vimrc
    sed -i 's/airline_theme=\"nord\"/airline_theme=\"silver\"/g' ~/.vimrc
    # Emacs
    sed -i "s/doom-nord/doom-nord-light/g" ~/.doom.d/config.el
    sh ~/.emacs.d/bin/doom sync
    # Code
    sed -i "s/Nord/Atom One Light/g" ~/.config/Code/User/settings.json
    # Sublime
    sed -i "s/Nord\/Nord.sublime-color-scheme/One Half Color Schemes\/OneHalfLight.tmTheme/g" /home/mir/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    # Zathura
    cp ~/.config/zathura/zathurarc-light ~/.config/zathura/zathurarc
elif [ $1 == "n" ]
then
    # Firefox
    cp -vr ~/.mozilla/firefox/3ccio4xn.default-nightly/chrome/userChrome-nord.css ~/.mozilla/firefox/3ccio4xn.default-nightly/chrome/userChrome.css
    # Wallpaper
    feh --bg-fill /home/mir/Pictures/Anime/ETUFu1PU8AAiTvH.jpg
    # Alacritty
    cp ~/.config/alacritty/alacritty-nord.yml ~/.config/alacritty/alacritty.yml
    # Kitty
    sed -i "s/polar/nord/g" ~/.config/kitty/kitty.conf
    # Global theme
    dconf dump '/org/cinnamon/' > ~/.dconf/cinnamon.dconf
    sed -i "s/theme='WhiteSur-light'/theme='Nord'/g" ~/.dconf/cinnamon.dconf
    sed -i "s/name='WhiteSur-light'/name='Adapta-Nokto'/1" ~/.dconf/cinnamon.dconf
    dconf load '/org/cinnamon/' < ~/.dconf/cinnamon.dconf
    # Rofi
    sed -i "s/light/nord/g" ~/.config/rofi/config.rasi
    # Vim
    sed -i 's/colorscheme one/colorscheme nord/g' ~/.vimrc
    sed -i 's/airline_theme=\"silver\"/airline_theme=\"nord\"/g' ~/.vimrc
    # Emacs
    sed -i 's/doom-nord-light/doom-nord/g' ~/.doom.d/config.el
    sh ~/.emacs.d/bin/doom sync
    # Code
    sed -i "s/Atom One Light/Nord/g" ~/.config/Code/User/settings.json
    # Sublime
    sed -i "s/One Half Color Schemes\/OneHalfLight.tmTheme/Nord\/Nord.sublime-color-scheme/g" /home/mir/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    # Zathura
    cp ~/.config/zathura/zathurarc-nord ~/.config/zathura/zathurarc
fi
